### ISSUE TITLE
.NET MAUI for windows Publish and install issue. Access Denied error

### ISSUE THREAD

**Issue by kamranattari4192** [dotnet/docs-maui#863] opened 2022-09-08 02:04 UTC
I published .NET MAUI Windows MSIX to sideload that is signed with a valid certificate. When I click .msix file, nothing happened because msix extension was not known on windows 10 by default. It seems that I have to install App Installer from Microsoft Store to recognise msix extension. After installing App Installer, I clicked on .msix file it showed me installer window, when I clicked on Install button it showed me following error: App installation failed with error message: Access is denied. (0x80070005). Why am I getting this error? Then I open power shell without elevated admin rights and run Install.ps1 script it showed me Add-AppxPackage : Deployment failed with HRESULT: 0x80070005, Access is denied. error. After that I run power shell with elevated admin rights, and run Install.ps1, then it installed my package. So it is installing sideload package only from powershell with admin rights. How can we make it installable by double clicking misx file without admin rights?

**Comment by adegeo** [comment] 2022-09-08 16:20
Duplicate of #862

**Closed as completed by adegeo** 2022-09-08 16:20 UTC
Labels: Pri3
