### ISSUE TITLE
Add how-to for using upgrade assistant

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/docs-maui#146] opened 2021-08-31 15:52 UTC
It is not clear how to use the upgrade assistant to convert Xamarin to Maui.

Should users run the upgrade assistant on the Android and iOS projects or just on the shared project.

I've tried it both ways and run into issues either way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment] 2021-08-31 16:10
Hi @MisinformedDNA 

AFAIK, there isn't a public build of the .NET upgrade assistant that includes support for converting a Xamarin project to .NET MAUI. Are you building it yourself from the GitHub repo?

Regardless, it's not ready for use yet. When it is, the docs will be updated and people directed to give it a go.

**Comment by MisinformedDNA** [comment] 2021-08-31 16:46
@davidbritch That's fine. Then this documentation should be updated to not recommend upgrade assistant:

> Use the .NET upgrade assistant for .NET MAUI to migrate your Xamarin.Forms projects to .NET MAUI single project

**Comment by juansturla** [comment] 2021-09-01 18:21
I think the upgrade assistant will be of great value. And it should be the recommended way of updating your Xamarin.Forms project to .NET MAUI. 
The problem is that it's not ready yet

**Comment by davidbritch** [comment] 2021-09-02 10:48
@MisinformedDNA I thought the preceding sentence took care of it: 

> The process for migrating a Xamarin.Forms app to .NET MAUI is *expected* to be:

**Comment by MisinformedDNA** [comment] 2021-09-02 14:33
@davidbritch Yeah, I didn't see that right away. But why have step by step instructions that don't work? 

I think it should either be removed or called out more clearly like 

## Roadmap

or 

**(In development)** The process for migrating a Xamarin.Forms app to .NET MAUI is expected to be:

**Comment by davidbritch** [comment] 2021-09-02 16:18
@MisinformedDNA The PMs wanted it the way it is, to illustrate how Xamarin.Forms apps will be migrated to MAUI once MAUI moves out of preview status.

**Comment by MisinformedDNA** [comment] 2021-09-02 18:45
That's fine. It just needs to be more clearly marked as such. Adding **(In development)** is a pretty small ask and is far less than what most MS Docs do.

**Comment by MisinformedDNA** [comment] 2021-09-02 21:05
I got the help I needed in https://github.com/dotnet/upgrade-assistant/issues/841. The migration worked for me with upgrade-assistant v0.3.242703.

**Comment by davidbritch** [comment] 2021-12-24 11:04
Closing as a dupe of #11

**Closed as completed by davidbritch** 2021-12-24 11:04 UTC
Labels: product-question, Pri2, dotnet-mobile/prod, dotnet-maui/tech
