### ISSUE TITLE
-p:RuntimeIdentifierOverride=win10-x64 throws an error on .NET8 (packaged CLI)

### ISSUE THREAD

**Issue by BurkusCat** [dotnet/docs-maui#2055] opened 2024-02-01 20:51 UTC
### Type of issue

Outdated article

### Description

When using `win10-x64` (or `win10-x86`), an error is thrown during build:
```
Error: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\8.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'win10-x64' is not recognized. See https://aka.ms/netsdk1083 for more information. [D:\a\maui-samples\maui-samples\8.0\Apps\WeatherTwentyOne\src\WeatherTwentyOne\WeatherTwentyOne.csproj::TargetFramework=net8.0-maccatalyst]
```

`win-x64` should be used instead. This allows the build to be successfully completed. However, I will note that the produced build fails to start.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/windows/deployment/publish-cli.md

### Document Version Independent Id

d0d904f8-2ff9-df92-6399-dc2ac35310b7

### Article author

@davidbritch

### Metadata

* ID: d0d904f8-2ff9-df92-6399-dc2ac35310b7 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment] 2024-02-02 12:58
Dupe of #2056

**Closed as completed by davidbritch** 2024-02-02 12:58 UTC
Labels: Pri2, dotnet-mobile/svc, dotnet-maui/subsvc

**Comment by BurkusCat** [comment] 2024-02-02 15:09
Hey, @davidbritch, just wanted to point out this issue is for the packaged instructions and other one was for the unpackaged instructions. I reported both pages :)
