### ISSUE TITLE
Clarify how to use DI with .NET MAUI and certain limitations with XAML

### ISSUE THREAD

**Issue by Eilon** [dotnet/docs-maui#1919] opened 2023-11-28 23:06 UTC
## Help make content visible

Search "dependency injection" in docs: https://learn.microsoft.com/en-us/search/?scope=.NET%20MAUI&view=net-maui-8.0&terms=dependency%20injection

And there's not much relevant content.

For example, Blazor has this DI doc: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-7.0

## Describe the new article

DI is a popular pattern in modern apps and used by default in .NET MAUI projects. But there is little in the way of MAUI-specific docs, including certain limitations of how it can be used in .NET MAUI.

TOC:

* DI fundamentals
* Explain what's in MauiProgram.cs by default
* Registering a service and consuming from pages/viewmodels
* Limitations of DI with XAML. This is inspired by the discussion of limitations with XAML static resources and DI here: https://github.com/dotnet/maui/issues/11485
* DI with .NET MAUI Blazor Hybrid apps

Abstract: This article describes how to use Dependency Injection (DI) in .NET MAUI applications to register and consume services throughout the app.

**Comment by Eilon** [comment] 2023-11-28 23:06
BTW I'm happy to work with someone on this doc.

**Comment by davidbritch** [comment] 2023-11-29 12:43
This has been planned since day 1, but is only just now bubbling to the top of the pile in terms of priorities. It's scheduled to be written this semester.

FYI: There is also https://learn.microsoft.com/en-us/dotnet/architecture/maui/dependency-injection

Closing as a dupe of https://github.com/dotnet/docs-maui/issues/671

**Closed as completed** 2023-11-29 12:43 UTC
Labels: duplicate, Pri3
