### ISSUE TITLE
There is no information on how to consume a resource from C#

### ISSUE THREAD

**Issue by koddek** [dotnet/docs-maui#730] opened 2022-08-01 15:22 UTC
I would like to see some information on how to consume a resource dictionary from C# code. For example, I have styles set for my controls in XAML resource dictionary, and I am using C# Markup. How do I attach the style from the resource dictionary to C# code control.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3578fc-a78a-c184-30be-692147e72c85
* Version Independent ID: 6e3578fc-a78a-c184-30be-692147e72c85
* Content: [Resource dictionaries - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/resource-dictionaries)
* Content Source: [docs/fundamentals/resource-dictionaries.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/resource-dictionaries.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment] 2022-08-01 15:40
Dupe of #548

**Closed as completed by davidbritch** 2022-08-01 15:40 UTC
Labels: Pri2, dotnet-mobile/prod, dotnet-maui/tech, :watch: Not Triaged
