### ISSUE TITLE
the device location is not turned on when I granted the permission in .net maui

### ISSUE THREAD

**Issue by 7875Vijay** [dotnet/docs-maui#2246] opened 2024-05-08 11:36 UTC
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/geolocation?view=net-maui-8.0&tabs=windows

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/geolocation.md

### Document Version Independent Id

88e0c605-3e8e-3b61-7e9e-a31b482f3274

### Article author

@davidbritch

### Metadata

* ID: 88e0c605-3e8e-3b61-7e9e-a31b482f3274 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment] 2024-05-30 10:44
Dupe of #2247

**Closed as completed by davidbritch** 2024-05-30 10:44 UTC
Labels: product-question, Pri1, dotnet-mobile/svc, dotnet-maui/subsvc
