### ISSUE TITLE
Separator lines - A distinct lack of specificity ...

### ISSUE THREAD

**Issue by rogersm-uwosh** [dotnet/docs-maui#1705] opened 2023-09-16 00:31 UTC
This page had the following "[CollectionView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.collectionview) does not include built-in separators. These can be provided, if desired, in the item template."

They are desired (at least in my case), but this is sorely lacking in specificity. I now have enough detail to go Google (or ChatGPT) the answer, but it would be nice if the page just told me, right here, how to accomplish this _extremely_ common task.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 56821f6d-0cf1-2330-a905-1107313bc8dc
* Version Independent ID: 56821f6d-0cf1-2330-a905-1107313bc8dc
* Content: [CollectionView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/)
* Content Source: [docs/user-interface/controls/collectionview/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/collectionview/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment] 2024-07-18 14:44
Closing as a dupe of #2349

**Closed as completed by davidbritch** 2024-07-18 14:44 UTC
Labels: doc-enhancement, Pri1, dotnet-mobile/prod, dotnet-maui/tech
