### ISSUE TITLE
Provide instructions for setting up hardware acceleration for the Android emulator

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs-maui#307] opened 2022-02-14 18:15 UTC
The .NET MAUI getting started steps walk you through creating and running your first app, but they don't mention the need to [setup hardware acceleration](https://docs.microsoft.com/xamarin/android/get-started/installation/android-emulator/hardware-acceleration). Without hardware acceleration the Android emulator is almost unusable. As a quick fix, we could reference the Xamarin doc as a prerequisite or installation step. We should also consider if we need to replicate the Xamarin doc in the .NET MAUI docs.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment] 2022-02-15 09:39
Dupe of #73

**Closed as completed by davidbritch** 2022-02-15 09:39 UTC
Labels: Pri1, dotnet-mobile/prod, dotnet-maui/tech, :watch: Not Triaged
