### ISSUE TITLE
MAUI Workloads Missing in Instructions

### ISSUE THREAD

**Issue by bugbytesinc** [dotnet/docs-maui#152] opened 2021-09-09 12:10 UTC
[Enter feedback here]

I used this page to guide the installation of VS Preview on a **fresh** W11 install on hardware.  I've had major headwinds.

First, there is no mention that maui-check must be invoked from an elevated environment.

Secondly, it misses all the maui-* workloads
(if maui check is suposto check that, there must be a bug somewhere)

And I still don't know why in visual studio I don't see my MAUI project templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment] 2021-09-09 19:06
Sorry this is happening! I'm going to close this as a duplicate of another issue. Seeing that this is the 2nd duplicate, I'm thinking that something may have changed in the install system. I'll open an issue in the maui repo to see what they say. Please follow along in the main issue.

**Comment by adegeo** [comment] 2021-09-09 19:07
Duplicate of #150

**Closed as completed by adegeo** 2021-09-09 19:07 UTC
Labels: support-request, Pri1, dotnet-mobile/prod, dotnet-maui/tech
