### ISSUE TITLE
Documentation still recommends deprecated Application.MainPage property

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/docs-maui#2485] opened 2024-09-12 12:33 UTC
### Type of issue

Outdated article

### Description

https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0#mainpage explains that the `Application.MainPage` property is deprecated from .NET 9 but [the documentation about MAUI windows](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows?view=net-maui-9.0#create-a-window) still uses this property as if it is not deprecated

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows?view=net-maui-9.0#create-a-window

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/windows.md

### Document Version Independent Id

c7dc34b7-8355-cff9-6754-c9fdefade29a

### Article author

@davidbritch

### Metadata

* ID: c7dc34b7-8355-cff9-6754-c9fdefade29a 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment] 2024-09-16 15:18
Dupe of #2426, which will hopefully be completed for the .NET MAUI 9 launch (but there's no guarantee as it's an incredibly big change to make to the samples/docs).

**Closed as completed by davidbritch** 2024-09-16 15:18 UTC
Labels: duplicate, Pri2, dotnet-mobile/svc, dotnet-maui/subsvc
