### ISSUE TITLE
No ".NET MAUI App"?

### ISSUE THREAD

**Issue by plettb** [dotnet/docs-maui#151] opened 2021-09-07 19:10 UTC
I've just followed the [installation instructions](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation), and "maui-check" passes with "Congratulations, everything looks great!".  However, when I try to create a new project in VS2022, ".NET MAUI App" is not in the list.  Entering "maui" in the search returns nothing.  What am I missing?

I'm on a brand new Windows 11 VM, with a brand new installation of VS2022.

Thanks!
Brad.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment] 2021-09-09 19:04
Hi! I'm going to close this as a duplicate of another issue. Please post in that issue while we try to figure this out. I did post instructions in that issue, the main one being, `run the workload install command as administrator`. Try that and see if it fixes things.

**Comment by adegeo** [comment] 2021-09-09 19:04
Duplicate of #150

**Closed as completed by adegeo** 2021-09-09 19:04 UTC
Labels: support-request, Pri2, dotnet-mobile/prod, dotnet-maui/tech

**Comment by plettb** [comment] 2021-09-14 03:11
I don't understand how #150 is even related, and I don't see anything on there that addresses this issue.  Am I missing something?
