### ISSUE TITLE
Backgrounding and DisplayDensityChanged missing from App Lifecycle page

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/docs-maui#578] opened 2022-05-31 16:55 UTC
The [App Lifecycle](https://docs.microsoft.com/dotnet/maui/fundamentals/app-lifecycle) page describes *most* of the application lifecycle events, but there are two missing, `Backgrounding` and `DisplayDensityChanged`.  These are listed on [this page](https://docs.microsoft.com/dotnet/maui/fundamentals/windows), but without much detail.

Additionally, the sample shown in the Windows section catches a platform-specific DPI changed event, and it's unclear if that is the same that is raised by `DisplayDensityChanged` or not.

```csharp
.OnPlatformMessage((window, args) =>
{
    if (args.MessageId == Convert.ToUInt32("0x02E0"))
    {
        // DPI has changed
    }
}));
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c2cef1-8fc3-6e53-cc28-393e00e31b85
* Version Independent ID: b2c2cef1-8fc3-6e53-cc28-393e00e31b85
* Content: [App lifecycle - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle)
* Content Source: [docs/fundamentals/app-lifecycle.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/app-lifecycle.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment] 2022-06-14 09:08
Largely a dupe of #403

**Closed as completed** 2023-01-03 14:38 UTC
Labels: doc-enhancement, Pri1, dotnet-mobile/prod, dotnet-maui/tech
