### ISSUE TITLE
Add Testing/Unit Testing documentation for MAUI?

### ISSUE THREAD

**Issue by datvm** [dotnet/docs-maui#1290] opened 2023-02-24 09:42 UTC
Right now the only thing I get when Google "MAUI app testing" is this video: https://learn.microsoft.com/en-us/events/dotnetconf-focus-on-maui/unit-testing-for-your-maui-applications. Can we please have it written instead? Thanks.

**Comment by davidbritch** [comment] 2023-03-31 11:05
Dupe of #288

**Closed as completed by davidbritch** 2023-03-31 11:05 UTC
Labels: Pri3, doc-idea
