### ISSUE TITLE
Google Play Console API Access is no more?

### ISSUE THREAD

**Issue by project-x51** [dotnet/docs-maui#2263] opened 2024-05-15 23:06 UTC
### Type of issue

Outdated article

### Description

Hi,

When I try to distribute my code from Visual Studio to the Google Play Console I need to enter information into the "Register Google API Access" dialog. The link in this dialog goes to an old article. The latest article (this one), discusses setting up "API Access" in the Google Play Console. That page no longer exists!

I'm a little confused about what to do now. I will have to continue manually deploying the code until the documentation is resolved.

This page shows the page while it still existed and Google was transitioning away. Now the page doesn't exist at all. I'm unsure how to setup this API access and for now its just more productive for me to manually do this.
https://support.google.com/googleplay/android-developer/thread/238643394/google-play-console-api-access-page-has-gone-away?hl=en

![image](https://github.com/dotnet/docs-maui/assets/40679862/1cdaa2d1-13aa-41ce-84fa-5fdf73bc9772)

I'm using Visual Studio 17.8.3. I know there is a newer version but I have an issue with it and these are the latest instructions I can find.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-google-play?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/publish-google-play.md

### Document Version Independent Id

52ddc473-7f14-f391-2589-1484ce1aa3be

### Article author

@davidbritch

### Metadata

* ID: 52ddc473-7f14-f391-2589-1484ce1aa3be 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment] 2024-09-17 09:04
Dupe of #2494

**Closed as completed by davidbritch** 2024-09-17 09:04 UTC
Labels: doc-bug, Pri2, dotnet-mobile/svc, dotnet-maui/subsvc
