### ISSUE TITLE
Seems incomplete: No links to a detailed step by step. No info on how to deploy from Visual Studio.

### ISSUE THREAD

**Issue by Jelgab** [dotnet/docs-maui#1013] opened 2022-10-19 19:54 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6c3b8a-6109-5ad5-ca05-fdaae8a9d66e
* Version Independent ID: 6b6c3b8a-6109-5ad5-ca05-fdaae8a9d66e
* Content: [Use the CLI to publish for Android - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-cli)
* Content Source: [docs/android/deployment/publish-cli.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/publish-cli.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment] 2023-05-15 15:35
Closing as a dupe of #760 and #937.

**Closed as completed by davidbritch** 2023-05-15 15:35 UTC
Labels: doc-enhancement, Pri1, dotnet-mobile/prod, dotnet-maui/tech
